version: "1.0"
services:
  redis:
    image: redis
    container_name: synapses-redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - ./data/redis-data:/data
    command: ["redis-server", "--appendonly", "yes"]
  redisinsight:
    image: redislabs/redisinsight:latest
    restart: always
    container_name: redisinsight
    volumes:
      - ./data/redisinsight-data:/data
    ports:
      - "5540:5540"
    user: "${UID}:${GID}"